#!/bin/sh

#   POSIX compliant script to capture 'TODO's in source code and automatically
#   create issues.
#   Copyright (C) 2022 Nicolai Brand 
#   
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# 1. first match any comment (// or /* or #)
# 2. then match any witespace after comment decleration
# 3. then keep the stuff to the right of the match
regex="((\/\/|\/\*|#)\s*?TODO:?)\K.*"
ignore="$(cat .gitignore)"

mkdir -p "issues"

for file in $(find *)
do
    # skip if filename in .gitignore
    [ $(echo "$ignore" | grep -v "$file") ] || continue
    # skip if filename is this file
    [ "./$file" = "$0" ] && continue
    grep -oP "$regex" "$file" | awk '{print $0 > "issues/"NR".txt"}'
done
